//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnceInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnceInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //*[@id=&quot;lstRascasTodos&quot;]/li/a.
        /// </summary>
        internal static string Nodo_Listado_Rascas {
            get {
                return ResourceManager.GetString("Nodo_Listado_Rascas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //header/div/div/h2.
        /// </summary>
        internal static string Nodo_Nombre_Rasca {
            get {
                return ResourceManager.GetString("Nodo_Nombre_Rasca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ./span[@class=&apos;precio&apos;].
        /// </summary>
        internal static string Nodo_Precio_Listado_Rascas {
            get {
                return ResourceManager.GetString("Nodo_Precio_Listado_Rascas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //ul[@class=&apos;premiosrascas&apos;].
        /// </summary>
        internal static string Nodos_Listado_Rasca {
            get {
                return ResourceManager.GetString("Nodos_Listado_Rasca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //div[@class=&quot;contenido&quot;]/h3.
        /// </summary>
        internal static string Nodos_PRasca {
            get {
                return ResourceManager.GetString("Nodos_PRasca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ./li.
        /// </summary>
        internal static string Nodos_Premio {
            get {
                return ResourceManager.GetString("Nodos_Premio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /rascas-todos.
        /// </summary>
        internal static string Path_rasca {
            get {
                return ResourceManager.GetString("Path_rasca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  con precio.
        /// </summary>
        internal static string Texto_MultiP {
            get {
                return ResourceManager.GetString("Texto_MultiP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Premios por cada serie de boletos de .
        /// </summary>
        internal static string TextoP {
            get {
                return ResourceManager.GetString("TextoP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www.juegosonce.es.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
    }
}
